/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	uint32_t volatile *pClkCtrlReg = (uint32_t *)0x4002104C;
	uint32_t volatile *pPortAModeReg = (uint32_t *)0x48000000;
	uint32_t volatile *pPortAOutReg = (uint32_t *)0x48000014;

	uint32_t volatile *pPortBModeReg = (uint32_t *)0x48000400;
	uint32_t volatile *pPortBInReg = (uint32_t *)0x48000410;

	uint8_t pinStatus;

	// 1. 포트 A, B 활성화
	*pClkCtrlReg |= (1 << 0);
	*pClkCtrlReg |= (1 << 1);

	// 2. 포트 A 5번핀 출력 설정
	// 2.1 11, 10번을 클리어
	*pPortAModeReg &= ~(3 << 10);
	// 2.2 11, 10을 01로 설정
	*pPortAModeReg |= (1 << 10);

	// 3. 포트 B 0번핀 입력 설정
	// 3.1 1, 0 번을 00 으로 설정
	*pPortBModeReg &= ~(0x3);

	while(1)
	{
		// 포트 B의 0번핀 읽기
		pinStatus = (uint8_t)(*pPortBInReg & 0x1);

		if(pinStatus)
		{
			// 3. 포트 A 5번핀 켜기
			*pPortAOutReg |= (1 << 5);
		}
		else
		{
			// 3. 포트 A 5번핀 끄기
			*pPortAOutReg &= ~(1 << 5);
		}
	}
}
