/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	uint32_t *pClkCtrlReg = (uint32_t *)0x4002104C;
	uint32_t *pPortAModeReg = (uint32_t *)0x48000000;
	uint32_t *pPortAOutReg = (uint32_t *)0x48000014;


	// 1. 포트 A 활성화
	//*pClkCtrlReg |= 0x01;
	*pClkCtrlReg |= (1 << 0);

	// 2. 포트 A 5번핀 모드 설정
	// 2.1 11, 10번핀을 클리어
	//*pPortAModeReg &= 0xFFFFF3FF;
	*pPortAModeReg &= ~(3 << 10);

	// 2.2 11, 10번을 01로 설정
	*pPortAModeReg |= (1 << 10);

	while(1)
	{
		// 3. 포트 A 5번핀 켜기
		*pPortAOutReg |= (1 << 5);

		for(uint32_t i=0; i < 100000; i++);

		// 3. 포트 A 5번핀 끄기
		*pPortAOutReg &= ~(1 << 5);

		for(uint32_t i=0; i < 100000; i++);
	}


}
