/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#include<stdint.h>
#include<stdio.h>

void delay(void)
{
	for(uint32_t i =0 ; i < 150000 ; i++);

}

int main(void)
{
	//peripheral register addresses
	uint32_t volatile *const pGPIOAModeReg  =  (uint32_t*)(0x48000000);
	uint32_t volatile *const pInPutDataReg  =  (uint32_t*)(0x48000010);
	uint32_t volatile *const pOutPutDataReg =  (uint32_t*)(0x48000014);
	uint32_t volatile *const pClockCtrlReg  =  (uint32_t*)(0x4002104C);
	uint32_t volatile *const pPullupDownReg =  (uint32_t*)(0x4800000C);

     //1.Enable the peripheral clock of GPIOA peripheral
	*pClockCtrlReg |= ( 1 << 0);


    // 2.configure PA4,PA5,PA6,PA7 as output (rows)
	*pGPIOAModeReg &= ~(0xFF << 8); //clear
	*pGPIOAModeReg |= (0x55 << 8);   //set


	// 3. configure PA8 , PA9, PA10, PA11 as input (columns)
    *pGPIOAModeReg &= ~(0xFF << 16);

	// 4.Enable internal pull-up resistors for PA8 PA9 PA10 PA11
    *pPullupDownReg &= ~(0xFF << 16);
    *pPullupDownReg |=  (0x55 << 16);

	while(1)
	{
		//make all rows HIGH
		*pOutPutDataReg |= (0x0f << 4);

		//make R1 LOW(PA4)
		*pOutPutDataReg &= ~( 1 << 4);

		//scan the columns
		//check C1(PA8) low or high
		if(!(*pInPutDataReg & ( 1 << 8))){
			//key is pressed
			delay();
			printf("1\n");
		}

		//check C2(PA9) low or high
		if(!(*pInPutDataReg & ( 1 << 9))){
			//key is pressed
			delay();
			printf("2\n");
		}

		//check C3(PA10) low or high
		if(!(*pInPutDataReg & ( 1 << 10))){
			//key is pressed
			delay();
			printf("3\n");
		}

		//check C4(PA11) low or high
		if(!(*pInPutDataReg & ( 1 << 11))){
			//key is pressed
			delay();
			printf("A\n");
		}


		//make all rows HIGH
		*pOutPutDataReg |= (0x0f << 4);
		//make R2 LOW(PA5)
		*pOutPutDataReg &= ~( 1 << 5);

		//scan the columns
		//check C1(PA8) low or high
		if(!(*pInPutDataReg & ( 1 << 8))){
			//key is pressed
			delay();
			printf("4\n");
		}

		//check C2(PA9) low or high
		if(!(*pInPutDataReg & ( 1 << 9))){
			//key is pressed
			delay();
			printf("5\n");
		}

		//check C3(PA10) low or high
		if(!(*pInPutDataReg & ( 1 << 10))){
			//key is pressed
			delay();
			printf("6\n");
		}

		//check C4(PA11) low or high
		if(!(*pInPutDataReg & ( 1 << 11))){
			//key is pressed
			delay();
			printf("B\n");
		}

		//make all rows HIGH
		*pOutPutDataReg |= (0x0f << 4);
		//make R3 LOW(PA6)
		*pOutPutDataReg &= ~( 1 << 6);

		//scan the columns
		//check C1(PA8) low or high
		if(!(*pInPutDataReg & ( 1 << 8))){
			//key is pressed
			delay();
			printf("7\n");
		}

		//check C2(PA9) low or high
		if(!(*pInPutDataReg & ( 1 << 9))){
			//key is pressed
			delay();
			printf("8\n");
		}

		//check C3(PA10) low or high
		if(!(*pInPutDataReg & ( 1 << 10))){
			//key is pressed
			delay();
			printf("9\n");
		}

		//check C4(PA11) low or high
		if(!(*pInPutDataReg & ( 1 << 11))){
			//key is pressed
			delay();
			printf("C\n");
		}

		//make all rows HIGH
		*pOutPutDataReg |= (0x0f << 4);
		//make R4 LOW(PA7)
		*pOutPutDataReg &= ~( 1 << 7);

		//scan the columns
		//check C1(PA8) low or high
		if(!(*pInPutDataReg & ( 1 << 8))){
			//key is pressed
			delay();
			printf("*\n");
		}

		//check C2(PA9) low or high
		if(!(*pInPutDataReg & ( 1 << 9))){
			//key is pressed
			delay();
			printf("0\n");
		}

		//check C3(PA10) low or high
		if(!(*pInPutDataReg & ( 1 << 10))){
			//key is pressed
			delay();
			printf("#\n");
		}

		//check C4(PA11) low or high
		if(!(*pInPutDataReg & ( 1 << 11))){
			//key is pressed
			delay();
			printf("D\n");
		}

	}//while end

}
