/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	float d1 = -1.60217662e-19;
	printf("chargeE = %f\n", d1);
	printf("chargeE = %e\n", d1);

	double d2 = -1.60217662e-19;
	printf("chargeE = %0.28lf\n", d2);
	printf("chargeE = %0.8le\n", d2);
    /* Loop forever */
	for(;;);
}
