/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#include "main.h"

/*
	uint32_t *pClkCtrlReg =   (uint32_t*)0x40023830;
	uint32_t *pPortDModeReg = (uint32_t*)0x40020C00;
	uint32_t *pPortDOutReg =  (uint32_t*)0x40020C14; */

int main(void)
{
	// 주소는 변경하면 안되며 주소에 담긴 값은 프로그래머의 조작과 상관없이 변할 수 있음 -> 컴파일러가 최적화 안하게 함
	RCC_AHB2ENR_t volatile *const pClkCtrlReg   = ADDR_REG_AHB2ENR;
	GPIOx_MODE_t  volatile *const pPortAModeReg = ADDR_REG_GPIOA_MODE;
	GPIOx_ODR_t   volatile *const pPortAOutReg  = ADDR_REG_GPIOA_OD;

	//1. enable the clock for GPOID peripheral in the AHB1ENR (SET the 3rd bit position)
	pClkCtrlReg->gpioa_en = CLOCK_ENABLE;


	//2. configure the mode of the IO pin as output
	pPortAModeReg->pin_5 = MODE_CONF_OUTPUT;

	while(1)
	{
		//Set 5th bit of the output data register to make I/O pin-5 as HIGH
		pPortAOutReg->pin_5  = PIN_STATE_HIGH;

		//introduce small human observable delay
		//This loop executes for 300K times
		for(uint32_t i=0 ; i < DELAY_COUNT ; i++ );

		//Reset 5th bit of the output data register to make I/O pin-5 as LOW
		pPortAOutReg->pin_5  = PIN_STATE_LOW;

		for(uint32_t i=0 ; i < DELAY_COUNT ; i++ );
	}


	for(;;);
}
